# https://medium.com/@sapnarsy2612/setup-jenkins-master-slave-using-ansible-3e71eb4602e0
# jenkins μ„λ²„ μ„Έν…
---
- include_tasks: install_jenkins.yml
- include_tasks: install_docker.yml
- include_tasks: install_nginx.yml
